"""empty message

Revision ID: fd793b46cb83
Revises: c9fe678cbb03
Create Date: 2022-07-21 14:34:14.144090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd793b46cb83'
down_revision = 'c9fe678cbb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=9000),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.alter_column('user', 'password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=9000),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
